version: '3.7'

services:
  dev:
    image: node:latest
    working_dir: /app
    tty: true
    links:
      - mosquitto
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'

volumes:
  node_modules:
